steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args:
      - '-c'
      - "gcloud secrets versions access latest --secret=$BRANCH_NAME-${_APP_NAME} --format='get(payload.data)' | tr '_-' '/+' | base64 -d > .env"
  
  - name: 'gcr.io/cloud-builders/docker'
    dir: frontend
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - 'gcr.io/$PROJECT_ID/frontend:$BRANCH_NAME'
      - '--build-arg'
      - 'BACKEND_URL=http://backend-service:9000'
      - '--file'
      - 'Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/frontend:$BRANCH_NAME'

  - name: 'gcr.io/cloud-builders/docker'
    dir: backend
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - 'gcr.io/$PROJECT_ID/backend:$BRANCH_NAME'
      - '--build-arg'
      - 'ENV=${_ENV}'
      - '--file'
      - 'Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/backend:$BRANCH_NAME'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_APP_NAME}-$BRANCH_NAME-frontend'
      - '--image=gcr.io/$PROJECT_ID/frontend:$BRANCH_NAME'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8000' 
      - '--timeout=300s'
      - '--set-env-vars=BACKEND_URL=http://backend-service:9000'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_APP_NAME}-$BRANCH_NAME-backend'
      - '--image=gcr.io/$PROJECT_ID/backend:$BRANCH_NAME'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=9000' 
      - '--timeout=500s'
      - '--add-cloudsql-instances=${_CLOUDSQL_CONNECTION_NAME}'
      - '--set-env-vars=POSTGRES_USER=d3vuser,POSTGRES_PASSWORD=admin123,POSTGRES_DB=d3v-db,POSTGRES_HOST=34.70.0.83,POSTGRES_PORT=5432'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'pgadmin-$BRANCH_NAME'
      - '--image=dpage/pgadmin4'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=PGADMIN_DEFAULT_EMAIL=admin@admin.com,PGADMIN_DEFAULT_PASSWORD=pwdpwd'
      

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: us-central1
  _ENV: development
  _APP_NAME: d3v-app
  _SEVERITY: CRITICAL
  _CLOUDSQL_CONNECTION_NAME: feisty-return-438307-f5:us-central1:d3v-db

timeout: "1200s"
